### PR TITLE
Alex

### PR DESCRIPTION
**Pull request by alexrpedersen**
Card constructor with all 52 cards

### CODE REVIEW

**Review by will-ing — COMMENTED** [review]
The only thing it's missing is the var deck = []; (global variable). Other than that its clean.

**Comment by alexrpedersen** [comment]
Lol i felt like I was missing something

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by will-ing — COMMENTED** [review]
You are going to hate me for this but constructors names are capitalized. So card is Card. I would use the alt method to change all them at once.

**Comment by alexrpedersen** [comment]
Got it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
